CREATE DATABASE QLBH
ON PRIMARY(
	NAME = QLBH_data1,
	FILENAME = 'T:\QLBH_data1.mdf',
	SIZE = 10MB,
	MAXSIZE = 40MB,
	FILEGROWTH = 1MB
)
LOG ON(
	NAME = QLBH_Log,
	FILENAME = 'T:\QLBH.ldf',
	SIZE = 6MB,
	MAXSIZE = 8MB,
	FILEGROWTH = 1MB
);

--SP_HELPDB QLBH
--SP_SPACEUSED QLBH
--SP_HELPFILE QLBH

ALTER DATABASE QLBH
ADD FILEGROUP DuLieuQLBH;

ALTER DATABASE QLBH
ADD FILE(
	NAME = QLBH_data2,
	FILENAME = 'T:\QLBH_data2.ndf',
	SIZE = 6MB,
	MAXSIZE = 8MB,
	FILEGROWTH = 1MB
)TO FILEGROUP DuLieuQLBH;

--SP_HELPFILEGROUP 

ALTER DATABASE QLBH SET READ_ONLY;
ALTER DATABASE QLBH SET READ_WRITE;

ALTER DATABASE QLBH MODIFY FILE(
	NAME = QLBH_data1,
	SIZE = 50 MB
)

ALTER DATABASE QLBH MODIFY FILE(
	NAME = QLBH_log,
	SIZE = 10 MB
)