--USE master;
--DROP DATABASE QLSach;

CREATE DATABASE QLSach
ON PRIMARY
(
	NAME = QLSach_data,
	FILENAME = 'T:\QLTV\QLSach_Data.mdf',
	SIZE = 20MB,
	MAXSIZE = 40MB,
	FILEGROWTH = 1MB
)
LOG ON
(
	NAME = QLSach_Log,
	FILENAME = 'T:\QLTV\QLSach_Log.ldf',
	SIZE = 6MB,
	MAXSIZE = 8MB,
	FILEGROWTH = 1MB
);

--USE QLSach;

ALTER DATABASE QLSach
ADD FILEGROUP DuLieuSach;

ALTER DATABASE QLSach
ADD FILE(
	NAME = QlSach_Data2,
	FILENAME = 'T:\QLTV\QlSach_Data2.ndf',
	SIZE = 20MB,
	MAXSIZE = 40MB,
	FILEGROWTH = 1MB
) TO FILEGROUP DuLieuSach;

ALTER DATABASE QLSach
MODIFY FILEGROUP DuLieuSach READONLY;