CREATE DATABASE QLSV;

USE QLSV;

CREATE TABLE LOP(
	MaLop char(5) NOT NULL PRIMARY KEY,
	TenLop NVarchar(20) not null,
	SiSoDuKien Int, 
	NgayKhaiGiang DateTime
)
CREATE TABLE SINHVIEN(
	MaSV char(5) NOT NULL PRIMARY KEY, 
	TenHo NVarchar(40)NOT NULL, 
	NgaySinh DateTime, 
	MaLop char(5)
	FOREIGN KEY (MaLop) REFERENCES LOP(MaLop)
)

CREATE TABLE MONHOC(
	MaMH char(5) NOT NULL PRIMARY KEY, 
	Tenmh Nvarchar(30), 
	SoTC int
)

CREATE TABLE KETQUA(
	MaSV char(5) NOT NULL, 
	MaMH char(5) NOT NULL, 
	Diem real,
	PRIMARY KEY(MaSV,MaMH),
	FOREIGN KEY (MaSV) REFERENCES SINHVIEN(MaSV),
	FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH)
)

-- LOP
INSERT INTO LOP VALUES ('L001', N'CNTT1', 30, '2023-09-01');
INSERT INTO LOP VALUES ('L002', N'CNTT2', 25, '2023-09-05');
INSERT INTO LOP VALUES ('L003', N'KTPM', 20, '2023-09-10');

-- MONHOC
INSERT INTO MONHOC VALUES ('MH01', N'Cơ Sở Dữ Liệu', 45);
INSERT INTO MONHOC VALUES ('MH02', N'Lập Trình C#', 60);
INSERT INTO MONHOC VALUES ('MH03', N'Mạng Máy Tính', 50);

-- SINHVIEN
INSERT INTO SINHVIEN VALUES ('SV01', N'Nguyễn Văn A', '2002-01-01', 'L001');
INSERT INTO SINHVIEN VALUES ('SV02', N'Lê Thị B', '2002-02-02', 'L002');
INSERT INTO SINHVIEN VALUES ('SV03', N'Trần Văn C', '2002-03-03', 'L003');

-- KETQUA
INSERT INTO KETQUA VALUES ('SV01', 'MH01', 8.5);
INSERT INTO KETQUA VALUES ('SV02', 'MH02', 7.0);
INSERT INTO KETQUA VALUES ('SV03', 'MH03', 9.0);
